services:
  redis:
    image: redis:alpine
    container_name: fresio-dev-redis
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=password
  database:
    image: postgres:alpine
    container_name: fresio-dev-database
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    volumes:
      - fresio_dev_db_data:/var/lib/postgresql/data

volumes:
  fresio_dev_db_data: