services:
  redis:
    image: redis:alpine
    container_name: fresio-prd-redis
    environment:
      - REDIS_PASSWORD=password
      -
  database:
    image: postgres:alpine
    container_name: fresio-prd-database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    volumes:
      - fresio_prd_db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: always

volumes:
  mongodb_data:
    name: fresio-prd-mongodb-data