from enum import Enum


class ErrorCode(str, Enum):
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
    INVALID_ACCESS_TOKEN = "INVALID_ACCESS_TOKEN"

    INVALID_GOOGLE_CODE = "INVALID_GOOGLE_CODE"
    USER_NOT_FOUND = "USER_NOT_FOUND"
    USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS"

    HARDWARE_ALREADY_REGISTERED = "HARDWARE_ALREADY_REGISTERED"
